version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./weights:/app/weights
      - ./uploads:/app/uploads
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    ports:
      - "8931:8931"
    depends_on:
      - api
    environment:
      - PYTHONUNBUFFERED=1
      - API_URL=http://api:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8931/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
